### ISSUE TITLE
Redirect source URLs are not handled

### ISSUE THREAD

**Issue by Icohedron** [AdoptOpenJDK/install-jdk#12]
URL sources which redirect are not handled by the action.
Example SDK source: [https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz)
![image](https://user-images.githubusercontent.com/5418647/109395879-edf77f80-78eb-11eb-96c0-2432966b79c2.png)

**Comment by karianna** [comment]
We are no longer enhancing this legacy action.  Please see the official GitHub setup-java action
