### ISSUE TITLE
Add flags for TEST_IMAGES_REQUIRED and DEBUG_IMAGES_REQUIRED

### ISSUE THREAD

**Issue by Icohedron** [AdoptOpenJDK/install-jdk#14]
Similarly to the Jenkins Grinder, there should be options for setting the flags TEST_IMAGES_REQUIRED and DEBUG_IMAGES_REQUIRED
![image](https://user-images.githubusercontent.com/5418647/109561252-263cc080-7a9a-11eb-8a86-512dec211c0a.png)

**Comment by karianna** [comment]
We are no longer enhancing this legacy action.  Please see the official GitHub setup-java action
