### ISSUE TITLE
Support Eclipse Temurin distribution

### ISSUE THREAD

**Issue by reneleonhardt** [AdoptOpenJDK/install-jdk#22]
As [AdoptOpenJDK has been transferred to Adoptium](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/), I suggest following the upstream project and introduce a configuration parameter `distribution` for the new [Eclipse Temurin](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#eclipse-temurin) runtime.

**Comment by TheMrMilchmann** [comment]
This action uses the AdoptOpenJDK API which already provides the latest Temurin builds.

Temurin builds are currently available for 8, 11, 16 and (not quiet yet) 17. For any other version, only the old AdoptOpenJDK build is available and installed instead. I'm not aware of any plans to rebuild older JDKs. Thus, when the action will be updated to use the Adoptium API (which does not provide the old builds), some JDK versions won't be supported anymore. I believe that this behavior eliminates the need to select a distribution (at least between Temurin and Adopt builds).

**Comment by reneleonhardt** [comment]
Thank you for this project and clearing this up, with this solution for the near future people could compare an old AdoptOpenJDK version with the new Temurin version if they want, so I'm closing the issue.

If you think it's necessary you can avoid (my) confusion by stating this background in the readme, then everyone knows what distribution to expect for which versions.
