### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by valdar** [AdoptOpenJDK/install-jdk#41]
As per the title,  when I use this action I get this warning from GitHub:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: AdoptOpenJDK/install-jdk@v1.1.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

Can this be upgraded?

Thanks in advance.

**Comment by smlambert** [comment]
While it is possible, I note that this repository is not actively being worked on.  

Are you able to shift to using the [setup-java GitHub action](https://github.com/actions/setup-java) for your work?  It is being actively maintained.

**Comment by valdar** [comment]
Yep, thanks for the suggestion. Done that.
